name: ci

on:
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: aflplusplus/aflplusplus
      options: --cpus 1
    steps:
      - name: Install
        shell: bash
        run: apt-get update -y -qq && apt-get install -y -qq g++ ninja-build cmake make python-is-python3 libssl-dev pip gh python3-requests curl zip unzip tar pkg-config
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: Checkout Duckdb ALF++
        uses: actions/checkout@v4
        with:
          repository: duckdblabs/duckdb_aflplusplus
          ref: 'main'
          token: ${{ secrets.AFL }}
      - run: cat ${{ secrets.AFL }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ vars.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       -
#         name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           push: true
#           tags: ${{ vars.DOCKERHUB_USERNAME }}/clockbox:latest
