name: ci

on:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file_type: [ 'csv', 'json', 'parquet', 'duckdb', 'wal' ]
    steps:
      - name: Run AFL++ Setup
        run: |
          cd duckdb_aflplusplus
      - name: Checkout Duckdb AFL++
        uses: actions/checkout@v4
        with:
          repository: duckdblabs/duckdb_aflplusplus
          ref: 'main'
          token: ${{ secrets.AFL }}
          
      - run: sed -i 's/3600/30/g' Makefile
      
      # - name: Verify directory structure
      #   run: |
      #     ls -la
      #     ls -la src
      #     ls -la scripts
      - name: Set up Docker environment
        run: |
          docker --version
          docker pull aflplusplus/aflplusplus

      - name: Start AFL++ container
        run: |
          # Run the container in detached mode, naming it 'afl-container'
          docker run --name afl-container -d aflplusplus/aflplusplus sleep infinity

      - name: Copy directories into container
        run: |
          # Create necessary directories in the container and copy files
          docker exec -w / afl-container mkdir -p duckdb_aflplusplus
          docker cp src afl-container:/duckdb_aflplusplus/src
          docker cp scripts afl-container:/duckdb_aflplusplus/scripts
          docker exec afl-container mkdir -p /duckdb_aflplusplus/build
          docker exec afl-container mkdir -p /duckdb_aflplusplus/corpus
          docker exec afl-container mkdir -p /duckdb_aflplusplus/results
      - name: compile
        continue-on-error: true
        run: |
          make compile-fuzzers-CI
          make fuzz-${{ matrix.file_type }}-file
          # make afl-down
      - name: check
        run: |
          count=$(ls fuzz_results/csv_file_fuzzer/default/crashes | wc -l)
          if [ $count -eq 0 ]; then
            echo EMPTY
          else
            echo CRASHES 📌📌📌
          fi
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
