name: ci

on:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest

    container:
      image: aflplusplus/aflplusplus
      options: --cpus 1

    steps:
      - name: Checkout Duckdb AFL++
        uses: actions/checkout@v4
        with:
          repository: duckdblabs/duckdb_aflplusplus
          ref: 'main'
          token: ${{ secrets.AFL }}
          path: duckdb_aflplusplus

      - name: Install Dependencies
        run: |
          apt-get update -y -qq
          apt-get install -y -qq g++ cmake make ninja-build libssl-dev

      - name: Run AFL++ Setup
        run: |
          cd duckdb_aflplusplus
          make afl-up
